// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArcgANp0K5ebTnUDoO0uUirMkTNOCtZEg',
    appId: '1:841467742007:web:447933ac9730e6c7c73cb2',
    messagingSenderId: '841467742007',
    projectId: 'messaging-bcc60',
    authDomain: 'messaging-bcc60.firebaseapp.com',
    storageBucket: 'messaging-bcc60.appspot.com',
    measurementId: 'G-THQ06NW5LR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwE5NLn-EkkoedtAUDymmAmKHhR2wNDhw',
    appId: '1:841467742007:android:61c3b6209fa48f15c73cb2',
    messagingSenderId: '841467742007',
    projectId: 'messaging-bcc60',
    storageBucket: 'messaging-bcc60.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkLXZ4NhcNeOqf1TikFWUD59HZl2fuU-k',
    appId: '1:841467742007:ios:1e963c9c140364dac73cb2',
    messagingSenderId: '841467742007',
    projectId: 'messaging-bcc60',
    storageBucket: 'messaging-bcc60.appspot.com',
    iosBundleId: 'com.example.income',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkLXZ4NhcNeOqf1TikFWUD59HZl2fuU-k',
    appId: '1:841467742007:ios:935f1518687e1fdfc73cb2',
    messagingSenderId: '841467742007',
    projectId: 'messaging-bcc60',
    storageBucket: 'messaging-bcc60.appspot.com',
    iosBundleId: 'com.example.income.RunnerTests',
  );
}
